// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_project.Models;

#nullable disable

namespace Web_project.Migrations
{
    [DbContext(typeof(CoffeeContext))]
    partial class CoffeeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Web_project.Models.Agent", b =>
                {
                    b.Property<int>("AgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgentId"), 1L, 1);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AgentId");

                    b.HasIndex("CityId");

                    b.ToTable("Agents");

                    b.HasData(
                        new
                        {
                            AgentId = 1,
                            CityId = 1,
                            Name = "Ahmad",
                            Password = "123",
                            PhoneNumber = "0599004201",
                            Role = "Admin",
                            Salary = 4000m
                        },
                        new
                        {
                            AgentId = 2,
                            CityId = 2,
                            Name = "Sara",
                            Password = "456",
                            PhoneNumber = "0599540002",
                            Role = "User",
                            Salary = 3500m
                        },
                        new
                        {
                            AgentId = 3,
                            CityId = 2,
                            Name = "Mohammad",
                            Password = "453",
                            PhoneNumber = "0599005502",
                            Role = "User",
                            Salary = 3500m
                        },
                        new
                        {
                            AgentId = 4,
                            CityId = 1,
                            Name = "Dania",
                            Password = "436",
                            PhoneNumber = "0599044002",
                            Role = "User",
                            Salary = 3530m
                        },
                        new
                        {
                            AgentId = 5,
                            CityId = 2,
                            Name = "Sami",
                            Password = "156",
                            PhoneNumber = "0599034002",
                            Role = "User",
                            Salary = 3500m
                        },
                        new
                        {
                            AgentId = 6,
                            CityId = 4,
                            Name = "Ameed",
                            Password = "236",
                            PhoneNumber = "0599004302",
                            Role = "User",
                            Salary = 3500m
                        });
                });

            modelBuilder.Entity("Web_project.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            Name = "Jenin"
                        },
                        new
                        {
                            CityId = 2,
                            Name = "Nablus"
                        },
                        new
                        {
                            CityId = 3,
                            Name = "Ramallah"
                        },
                        new
                        {
                            CityId = 4,
                            Name = "Jerusalem"
                        });
                });

            modelBuilder.Entity("Web_project.Models.Agent", b =>
                {
                    b.HasOne("Web_project.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });
#pragma warning restore 612, 618
        }
    }
}
